### ISSUE TITLE
(Request) File Recorder

### ISSUE THREAD

**Issue by rhilfers** [ExpediaDotCom/haystack-client-python#7]
Users should be able to instantiate a tracer with a file-based span recorder

**Comment by shreyaa-sharma** [comment]
@rhilfers : Can you help elaborate more on this.

**Comment by rhilfers** [comment]
I was asked if there was an ability to write to a file with the python library, similar to the node dispatcher here: library's https://github.com/ExpediaDotCom/haystack-client-node/blob/master/src/dispatchers/file.ts
 
This issue proposes an enhancement to satisfy that request

**Comment by rhilfers** [comment]
this can easily be accomplished with the logging module using the current LoggerRecorder and attaching a FileHandler to the "haystack" logger

**Comment by rhilfers** [comment]
closed with viable workaround
